### ISSUE TITLE
Complete automation of manual release testing

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#107]
Growing our e2e test suite to hopefully replace most of manual release testing. 

As we QA an item in the sprint. Determine if it needs to have a new e2e test added. When you are thinking about creating a release test go ahead and automate that instead of adding to our backlog of manual tests.  NOTE: this is not constrained to just release tests. Feel free to add more that present value. 

Since the suite is growing there likely will need to be some separation of what runs. Introducing a daily suite run that runs every e2e test and scaling down the build suite to be more of a smoke/sanity check. Use[ protractor suites](https://www.protractortest.org/#/page-objects#configuring-test-suites) to separate the runs.  In our world of code the suites are currently defined in the [grunt file](https://github.com/medic/cht-core/blob/631b63cfd671f6a1f27a10a00476af4e5fc77bc6/Gruntfile.js#L759). 

Another option we can use is the grep command and tag tests.  This would be more useful if we are finding that we need to cherry pick tests from different files.   `it('should allow DB admins to POST to _changes @smoke', () => {})`.  Which we should be able to define in the grunt options. Will need exploration.

**Comment by garethbowen** [comment]
Finish automation of all tests in this board: https://github.com/medic/cht-release-testing/projects/79

**Comment by tatilepizs** [comment]
All the tickets from the board were successfully automated and merged in `master`
