### ISSUE TITLE
Move Android test cases from spread sheet to github issues

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#112]
To get our testing process for the android app in line with the rest of our testing process. 

1. Create test case issues in medic-release-test project using the doc [here](https://docs.google.com/spreadsheets/d/11E5ueMiMZStUaDsbu_hHEtbnWTP5l92T26tgiHv7aeo/edit#gid=1699575692). 
1. Ensure to label them as Android App 
1. Update Readme on how to create an android release test project. 
   - Update the `labels` in `config.js`
   - Run the script as detailed in the readme to generate a test project.

**Comment by ngaruko** [comment]
done - once off
