### ISSUE TITLE
Process a pregnancy visit report via SMS on standard config as restricted user on mobile app

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#18]
**User**: Restricted User
**Site**: Standard config site
**Platform**:  Mobile App
**Test Steps**:
Using a pregnant woman
Process a pregnancy visit form via SMS (V form) from the admin page. Use the correct phone number associated to the contact. 

**Expected Result**:
Make sure the condition card updates to reflect the visit
Check the record in Reports to make sure the appropriate outgoing SMS is generated

**Comment by tatilepizs** [comment]
## Testing plan for MoH Uganda upgrade

**cht-core version:** 4.1
**cht-android version:** 0.8.5

| Tester | Phone details | Android version | Results | Notes |
|-|-|-|-|-|
| Bede | | | | |
| Lorena | | | | |
| Tatiana | | | | |
