### ISSUE TITLE
Performance Timing on Standard config with seeded date. 

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#2]
**User**: Restricted User
**Site**: Standard config site
**Platform**:  Chrome Desktop, Mobile App
**Test Steps**:
Download [this](https://github.com/medic/cht-core/tree/master/tests/scalability/csv) CSVs and seed data using [CSV-To-Docs](https://github.com/medic/medic-docs/blob/master/configuration/csv-to-docs.md)
Preform tests scenarios outlined [here](https://docs.google.com/spreadsheets/d/13GW_gpZElcmW9AOs5r1EXwKligCDECdHVP_3aNcwqhw/edit#gid=1134415907)
Times should be similar. Preferably less but understandably we may not be working to improve those times. 

**Detailed Steps:**
Ensure the environment has been wiped and the data has been seeded.
Clear app cache on browser and mobile devices.

**Chrome Desktop:**
Navigate to the login page
Enter offline user account ac1 creds. 
Press login and start stop watch.  Record the time until the app is displayed to be usable. 
Navigate to the About Page. 
Press Reload and start stop watch. Record the time until the app returns to the about page. 
Press the Contacts tab and start stop watch. Record the time until the first contact loads and all spinners are gone. 
Press the Reports tab and start stop watch. Record the time until the reports left hand side completely loads.
Find the first New Pregnancy in the reports list. 
Click the New Pregnancy and start stop watch. Record the time until the report is loaded in the right hand side. 
Navigate to a child's profile and Process Child Assessment. Record the time from clicking the form in the menu to complete. 
Clear App cache in browser. Repeat the process a total of 3 times to get an average. 
**_NOTE_**: For memory after load and service worker memory, use dev tools >> **Memory's tab** >> 
![image](https://user-images.githubusercontent.com/6979995/135193014-fe0bc1d3-217d-4f42-884e-4255d9724528.png)

 **Phone Process:**
Navigate to the login page
Enter offline user account ac1 creds. 
Press login and start stop watch.  Record the time until the app is displayed to be usable. 
Navigate to the About Page. 
Press Reload and start stop watch. Record the time until the app returns to the about page. 
Press the Contacts tab and start stop watch. Record the time until the contact list loads.
Press the Reports tab and start stop watch. Record the time until the reports list is loaded.
Find the first New Pregnancy in the reports list. 
Click the New Pregnancy and start stop watch. Record the time until the report is loaded.
Navigate to a child's profile and Process Child Assessment. Record the time from clicking the form in the menu to complete. 
Clear App cache in mobile app settings. Repeat the process a total of 3 times to get an average.

**Comment by lorerod** [comment]
**User:** district_admin
**Config:** Standard
**cht-core version:**  3.15
**Environment:** Local with docker
**Platform:** Mobile App
**Phone:** Sony Xperia Z1
**Android Version:** 5.1.1
**Android System WebView Version:** 95.0.4638.74

**Compared:**
**APK 1:**  [cht-android-v0.8.0-5-unbranded-xwalk-armeabi-v7a-release.apk](https://github.com/medic/cht-android/releases/download/v0.8.0-5/cht-android-v0.8.0-5-unbranded-xwalk-armeabi-v7a-release.apk)
**APK 2:**  [cht-android-v1.0.0-alpha.1-unbranded-armeabi-v7a-release.apk](https://github.com/medic/cht-android/releases/download/untagged-bcd7f7e7b0d517f6e8e8/cht-android-v1.0.0-alpha.1-unbranded-armeabi-v7a-release.apk)

Results can be found in [here](https://docs.google.com/spreadsheets/d/13GW_gpZElcmW9AOs5r1EXwKligCDECdHVP_3aNcwqhw/edit#gid=1018310593) on "Android 1.0 | cht-core 3.15 | apk v0.8 vs apk v1.0" tab.
@garethbowen

**Comment by garethbowen** [comment]
@lorerod Thank you, that's great! Could you also let me know which version of the android webview you have on the device?

**Comment by lorerod** [comment]
Of course @garethbowen my Sony Xperia Z1 has Android System WebView Version 95.0.4638.74 installed

**Comment by craig-landry** [comment]
For easy skimming, here are the averages from that linked spreadsheet in GitHub/Markdown format:

| Test - Sony Xperia Z1 - Android 5.1.1 - cht-core 3.15  | APK: cht-android-v0.8.0-5-unbranded-xwalk-armeabi-v7a-release.apk  | APK: cht-android-v1.0.0-alpha.1-unbranded-armeabi-v7a-release.apk  |
| ------------ | ------------ | ------------ |
| Initial Load (Fetching 1882 docs)  | 0:03:14  | 0:01:35  |
| Refreshing after initial replication  | 0:00:10  | 0:00:03  |
| Loading Contacts Tab.  | 0:00:17  |  0:00:12 |
| Loading reports tab  | 0:00:23  | 0:00:21  |
|  Loading a specific report(New Pregnancy) | 0:00:04  |  0:00:02 |
| Track opening a form(New Pregnancy)  | 0:00:05  | 0:00:04  |
| Loading Tasks Tab.  | 0:00:02  | 0:00:01  |

**Comment by lorerod** [comment]
@craig-landry I took the liberty of correcting the initial load average of v0.8 on your comment. Hope it is ok.

**Comment by craig-landry** [comment]
> @craig-landry I took the liberty of correcting the initial load average of v0.8 on your comment. Hope it is ok.

ohh thank you! That was a big mistake. The correct value is wonderful :)

**Comment by tatilepizs** [comment]
### 3.16

Tested with two different phones:

- Samsung Galaxy A01 - Android 10 - Android System WebView Version: 102.0.5005.78
- Alcatel Onetouch 50560 - Android 5.1.1 - Android System WebView Version: 95.0.4638.74

Details about the test [here](https://docs.google.com/spreadsheets/d/13GW_gpZElcmW9AOs5r1EXwKligCDECdHVP_3aNcwqhw/edit?pli=1#gid=108696740)

**Comment by tatilepizs** [comment]
## Testing plan for MoH Uganda upgrade

**cht-core version:** 4.1
**cht-android version:** 0.8.5

| Tester | Phone details | Android version | Results | Notes |
|-|-|-|-|-|
| Bede | | | | |
| Lorena | | | | |
| Tatiana | | | | |
