### ISSUE TITLE
Add a pregnancy visit to pregnant woman on standard config as restricted user on mobile app

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#20]
**User**: Restricted User
**Site**: Standard config site
**Platform**:  Mobile App
**Test Steps**:
Using a pregnant woman
Process a pregnancy visit form.

**Expected Result**:
The pregnancy condition card should update
The report should be associated to the woman. 
The targets should be updated. 
Ensure outgoing SMS is generated for the report submission.

**Comment by tatilepizs** [comment]
## Testing plan for MoH Uganda upgrade

**cht-core version:** 4.1
**cht-android version:** 0.8.5

| Tester | Phone details | Android version | Results | Notes |
|-|-|-|-|-|
| Bede | | | | |
| Lorena | | | | |
| Tatiana | | | | |
