### ISSUE TITLE
Register a pregnancy with standard config as restricted user on mobile app

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#22]
**User**: Restricted User
**Site**: Standard config site
**Platform**: Mobile App
**Test Steps**:
Add a new woman of child bearing age.
Process the pregnancy form for this woman

**Expected Result**:
The woman's profile card gets a medic id
The pregnancy condition card is displayed
The SMS/task schedule for pregnancy is generated
The targets page is updated with new pregnancy

**Comment by tatilepizs** [comment]
## Testing plan for MoH Uganda upgrade

**cht-core version:** 4.1
**cht-android version:** 0.8.5

| Tester | Phone details | Android version | Results | Notes |
|-|-|-|-|-|
| Bede | | | | |
| Lorena | | | | |
| Tatiana | | | | |
