### ISSUE TITLE
Process an assessment for a child under 5 as restricted user on mobile app

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#34]
**User:**  Restricted User
**Site:** LG config site
**Platform:** Mobile app
**Test Steps**:
Using a child under 5
Process an assessment report for the child. 

**Expected Result**:
The report should be associated to the child.
A new follow up task is generated.
The target for assessments should be updated.

**Comment by ngaruko** [comment]
Tested using [assessment forms from Muso](https://github.com/medic/config-muso/blob/master/forms/app/patient_assessment.xml).
![image](https://user-images.githubusercontent.com/6979995/125536139-2744392a-6292-46e5-9dac-8fb75a021204.png)
