### ISSUE TITLE
Process a delivery report for pregnant woman as restricted user

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#39]
**User:**  Restricted User
**Site:** LG config site
**Platform:** Chrome Desktop
**Test Steps**:
Using a woman with a pregnancy registered. 
Process a delivery report 

**Expected Result**:
The report should be associated to the person and the pregnancy condition card should disappear.

**Comment by ngaruko** [comment]
Please not: For LG, this process is done with the `delivery follow-up` report
