### ISSUE TITLE
Immunization workflow on standard as restricted user on mobile app

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#4]
**User**: Restricted User
**Site**: Standard config site
**Platform**:  Mobile App
**Step 1**:
Add a new child under 2 to your clinic using the SMS CW form. The health center needs to be configured with immunization use cases.  

**Expected**: Make sure the Medic ID field gets populated (you may have to wait briefly for Sentinel to generate the ID)
Check the record in Reports to make sure the appropriate SMS schedule is generated

**Step 2**:
Process an immunization visit form for the child through the mobile app.

**Expected**: Make sure the condition card updates to reflect the visit
Check the record in Reports to make sure the appropriate outgoing SMS is generated
Check the targets page to make sure the vaccines given this month widget updates (restricted users only)

**Step 3**:
Send an immunization form for the child using the SMS form.  

**Expected**:
Make sure the condition card updates to reflect the vaccination
Check the record in Reports to make sure the appropriate outgoing SMS is generated
Check the targets page to make sure the vaccines given this month widget updates (restricted users only)

**Comment by ngaruko** [comment]
Step 1:
Add a new child under 2 to your clinic using the SMS CW form. The health center needs to be configured with immunization use cases.

![image](https://user-images.githubusercontent.com/6979995/134604562-dd74be72-4bba-4707-b1fa-6e22c610ffcf.png)

Step 2:
Process an immunization visit form for the child through the web app.

![image](https://user-images.githubusercontent.com/6979995/134605161-bd67e158-c77f-4551-97a0-ee56d7887d98.png)

![image](https://user-images.githubusercontent.com/6979995/134605125-fa564d25-5f04-4c4d-bb74-f582e4f7839d.png)
Step 3:
Send an immunization form for the child using the SMS form.



![image](https://user-images.githubusercontent.com/6979995/134609039-dbeb422c-1e53-4eaa-8196-1502ffcd5530.png)
![image](https://user-images.githubusercontent.com/6979995/134609066-0c5da65c-407e-4c87-8d63-d811c7717e8c.png)

**Comment by lorerod** [comment]
**User:** CHW
**Config:** Standard
**Environment:** gamma.dev.medicmobile.org
**Platform:** Mobile App. APK generated with branch master
**Phone:** Galaxy A01 Core
**Android Version:** 10
**Android System WebView Version:** 97.0.4692.98

1. Add a new child under 2 to your clinic using the SMS CW form. The health center needs to be configured with immunization use cases.

- [X] Make sure the Medic ID field gets populated (you may have to wait briefly for Sentinel to generate the ID)


- [X] Check the record in Reports to make sure the appropriate SMS schedule is generated


2. Process an immunization visit form for the child through the mobile app.

- [X] Make sure the condition card updates to reflect the visit

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated

- [X] Check the targets page to make sure the vaccines given this month widget updates (restricted users only)

3. Send an immunization form for the child using the SMS form (IMM).

- [X] Make sure the condition card updates to reflect the vaccination

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated

- [X] Check the targets page to make sure the vaccines given this month widget updates

**Comment by tatilepizs** [comment]
**User:** CHW
**Config:** Standard
**Environment:** gamma
**Phone:** Huawei P20 lite
**Android Version:** 9
**Android System WebView Version:** 74.0.3729.136

<details>
<summary>New child under 2 years created (CW form).</summary>

![image](https://user-images.githubusercontent.com/94494491/156840469-6abe7f39-62cc-4151-9a08-a6b1d57e3d0a.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/156840784-4f2d531d-45f8-4eec-8217-67310a6e54bf.png)

</details>

<details>
<summary>Immunization visit created (mobile app). </summary>

![image](https://user-images.githubusercontent.com/94494491/156841236-16e6e4f2-fb87-4bb5-9911-dbbb2f6edee6.png)

</details>

<details>
<summary>Record in reports created with the outgoing SMS.</summary>

![image](https://user-images.githubusercontent.com/94494491/156841297-9a4ad2f1-7eba-46fe-b8c8-e9e1b110bce8.png)

</details>

<details>
<summary>Targets page updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/156841365-bc7cac20-7d69-41f1-9c52-9b54eb81b10b.png)

</details>

<details>
<summary>Immunization visit created (IMM form).</summary>

![image](https://user-images.githubusercontent.com/94494491/156841982-b53557a2-ff49-4643-84b8-6704040a7715.png)

</details>

<details>
<summary>Record in reports created with the outgoing SMS.</summary>

![image](https://user-images.githubusercontent.com/94494491/156842043-32a85c52-fa65-4740-9563-e39049d69847.png)

</details>

<details>
<summary>Targets page updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/156842101-515912d1-b905-41aa-8318-90a7ced60b6f.png)

</details>

**Comment by lorerod** [comment]
**User:** CHW
**Config:** Standard
**Environment:** gamma-cht.dev.medicmobile.org
**Platform:** Mobile App. APK generated with branch master
**Phone:** Galaxy A01 Core
**Android Version:** 10
**Android System WebView Version:** 97.0.4692.98

<details>
<summary>New child under 2 years created (CW form).</summary>

![Screenshot_20220316-163215](https://user-images.githubusercontent.com/21312057/158678574-17e6e83f-c9a9-460d-8b31-2571a323eb80.jpg)

</details>

<details>
<summary>Record in reports created.</summary>

![Screenshot_20220316-163306](https://user-images.githubusercontent.com/21312057/158678643-da2c99bd-c16c-40cf-ac0f-22c91b2e897f.jpg)

</details>

<details>
<summary>Immunization visit created (mobile app). </summary>

![Screenshot_20220316-163428](https://user-images.githubusercontent.com/21312057/158678682-c0c48faf-3528-4018-afa9-53c975444b01.jpg)

</details>

<details>
<summary>Record in reports created with the outgoing SMS.</summary>

![Screenshot_20220316-164607](https://user-images.githubusercontent.com/21312057/158678722-2f7945af-6647-4213-8190-d6aa5be040c7.jpg)

</details>

<details>
<summary>Targets page updated.</summary>

![Screenshot_20220316-164632](https://user-images.githubusercontent.com/21312057/158678750-d013739a-03a9-4403-9c84-5c417f52095a.jpg)

</details>

<details>
<summary>Immunization visit created (IMM form).</summary>

![Screenshot_20220316-164909](https://user-images.githubusercontent.com/21312057/158678800-a279fe2d-97d9-4e2b-91f9-6ecb30a07f76.jpg)

</details>

<details>
<summary>Record in reports created with the outgoing SMS.</summary>

![Screenshot_20220316-164921](https://user-images.githubusercontent.com/21312057/158678922-449c53b3-9b75-465a-a9a5-b0679140ecdb.jpg)

</details>

<details>
<summary>Targets page updated.</summary>

![Screenshot_20220316-164940](https://user-images.githubusercontent.com/21312057/158678965-1f937146-f8bc-4ea5-a030-82531408f99b.jpg)

</details>

**Comment by lorerod** [comment]
**User:** CHW
**Config:** Standard
**Environment:** gamma-cht.dev.medicmobile.org
**Platform:** Mobile App. APK generated with branch master
**Phone:** Galaxy A01 Core
**Android Version:** 10
**Android System WebView Version:** 97.0.4692.98

<details>
<summary>New child under 2 years created (CW form).</summary>

![Screenshot_20220425-192332](https://user-images.githubusercontent.com/21312057/165191726-d2855bcf-d95c-49b8-8dd0-8dc346433498.jpg)

</details>

<details>
<summary>Record in reports created.</summary>

![Screenshot_20220425-192457](https://user-images.githubusercontent.com/21312057/165191762-7f97ef8d-b261-4a73-8b12-1a1784071394.jpg)

</details>

<details>
<summary>Immunization visit created (mobile app). </summary>

![Screenshot_20220425-192645](https://user-images.githubusercontent.com/21312057/165191774-26974b4f-5bb9-4775-92e9-ab477f949951.jpg)

</details>

<details>
<summary>Record in reports created with the outgoing SMS.</summary>

![Screenshot_20220425-192719](https://user-images.githubusercontent.com/21312057/165191782-55c3ce4e-200c-4f58-af9f-4252ce851b10.jpg)

</details>

<details>
<summary>Targets page updated.</summary>

![Screenshot_20220425-192759](https://user-images.githubusercontent.com/21312057/165191798-e124b862-551c-4f8f-b009-21ddddceb0c4.jpg)

</details>

<details>
<summary>Immunization visit created (IMM form).</summary>

![Screenshot_20220425-193153](https://user-images.githubusercontent.com/21312057/165191820-9ab13f59-a02b-40f4-901d-173e89f799b2.jpg)

</details>

<details>
<summary>Record in reports created with the outgoing SMS.</summary>

![Screenshot_20220425-193207](https://user-images.githubusercontent.com/21312057/165191837-cc687588-44e2-4513-9e48-449129be554f.jpg)

</details>

<details>
<summary>Targets page updated.</summary>

![Screenshot_20220425-193244](https://user-images.githubusercontent.com/21312057/165191850-32182a7d-c69b-4da2-97f9-16fc0364b88b.jpg)


</details>

**Comment by tatilepizs** [comment]
## Testing plan for MoH Uganda upgrade

**cht-core version:** 4.1
**cht-android version:** 0.8.5

| Tester | Phone details | Android version | Results | Notes |
|-|-|-|-|-|
| Bede | | | | |
| Lorena | | | | |
| Tatiana | | | | |
