### ISSUE TITLE
Immunization workflow on standard as restricted user

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#5]
**User**: Restricted User
**Site**: Standard config site
**Platform**:  Chrome Desktop
**Step 1**:
Add a new child under 2 to your clinic using the SMS CW form. The health center needs to be configured with immunization use cases.  

**Expected**: Make sure the Medic ID field gets populated (you may have to wait briefly for Sentinel to generate the ID)
Check the record in Reports to make sure the appropriate SMS schedule is generated

**Step 2**:
Process an immunization visit form for the child through the web app.

**Expected**: Make sure the condition card updates to reflect the visit
Check the record in Reports to make sure the appropriate outgoing SMS is generated
Check the targets page to make sure the vaccines given this month widget updates (restricted users only)

**Step 3**:
Send an immunization form for the child using the SMS form.  

**Expected**:
Make sure the condition card updates to reflect the vaccination
Check the record in Reports to make sure the appropriate outgoing SMS is generated
Check the targets page to make sure the vaccines given this month widget updates (restricted users only)

**Comment by ngaruko** [comment]
Testing 3.12.
There is a xml parsing error in the console, ... on most forms on `standard`, will investigate and see if it is worth raising 
![image](https://user-images.githubusercontent.com/6979995/125384392-f957cd00-e3ec-11eb-8cd8-ec820995edc1.png)

**Comment by lorerod** [comment]
**Config:** Default
 **Environment:** gamma.dev
**Platform:** WebApp 
**Browser:** Chrome

1. Add a new child under 2 to your clinic using the SMS CW form. The health center needs to be configured with immunization use cases.

- [X] Make sure the Medic ID field gets populated (you may have to wait briefly for Sentinel to generate the ID)
<img width="466" alt="Make sure the Medic ID field gets populated " src="https://user-images.githubusercontent.com/21312057/152068522-de41ed3e-5686-4407-b0ea-44caff3c03d8.png">

- [X] Check the record in Reports to make sure the appropriate SMS schedule is generated
<img width="471" alt="Check the record in Reports to make sure the appropriate SMS schedule is generated" src="https://user-images.githubusercontent.com/21312057/152068536-f5575c37-64fb-4fa1-a580-e172b75a7b17.png">

2. Process an immunization visit form for the child through the web app.

- [X] Make sure the condition card updates to reflect the visit
<img width="222" alt="Make sure the condition card updates to reflect the visit" src="https://user-images.githubusercontent.com/21312057/152068614-b441165f-8882-4b2e-b6e8-f293a5872f74.png">

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated
<img width="354" alt="Check the record in Reports to make sure the appropriate outgoing SMS is generated" src="https://user-images.githubusercontent.com/21312057/152068644-29ec3f15-4031-486e-b2b8-9fe319ef2304.png">

- [X] Check the targets page to make sure the vaccines given this month widget updates (restricted users only)
<img width="118" alt="Check the targets page to make sure the vaccines given this month widget updates" src="https://user-images.githubusercontent.com/21312057/152068690-74865278-16fe-4a81-8d36-6893b689545b.png">

3. Send an immunization form for the child using the SMS form (IMM).

- [ ] Make sure the condition card updates to reflect the vaccination
- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated
<img width="359" alt="Check the record in Reports to make sure the appropriate outgoing SMS is generated2" src="https://user-images.githubusercontent.com/21312057/152068791-f561139c-c059-4120-b733-23b406eba0f8.png">

- [X] Check the targets page to make sure the vaccines given this month widget updates
<img width="123" alt="Check the targets page to make sure the vaccines given this month widget updates2" src="https://user-images.githubusercontent.com/21312057/152068841-9202de35-a98e-426a-8fa3-b71754a54f61.png">

4. Send an immunization form for the child using the SMS form (CH2).

- [X] Make sure the condition card updates to reflect the vaccination
<img width="222" alt="Make sure the condition card updates to reflect the vaccination CH2" src="https://user-images.githubusercontent.com/21312057/152068905-89e7581c-a9a7-428a-bbf8-fa85710f7dfe.png">

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated
<img width="352" alt="Check the record in Reports to make sure the appropriate outgoing SMS is generated  CH2" src="https://user-images.githubusercontent.com/21312057/152068929-a2813787-1923-4d0f-b83a-7a2d74ef1b53.png">

- [ ] Check the targets page to make sure the vaccines given this month widget updates

@ngaruko I added a step. Can you please help me confirm expected results of 3 and 4 are correct? Thanks!

**Comment by lorerod** [comment]
**Config:** Standard
 **Environment:** gamma.dev
**Platform:** WebApp 
**Browser:** Chrome

1. Add a new child under 2 to your clinic using the SMS CW form. The health center needs to be configured with immunization use cases.

- [X] Make sure the Medic ID field gets populated (you may have to wait briefly for Sentinel to generate the ID)
![Captura de Pantalla 2022-03-04 a la(s) 10 52 13](https://user-images.githubusercontent.com/21312057/156776782-3c3071df-c74d-4fff-89a4-63966820fe9f.png)

- [X] Check the record in Reports to make sure the appropriate SMS schedule is generated
![Captura de Pantalla 2022-03-04 a la(s) 10 52 55](https://user-images.githubusercontent.com/21312057/156776805-4954ea53-24ee-46ba-b0f7-d90ec62cdaa9.png)

2. Process an immunization visit form for the child through the web app.

- [X] Make sure the condition card updates to reflect the visit
![Captura de Pantalla 2022-03-04 a la(s) 10 54 54](https://user-images.githubusercontent.com/21312057/156776828-a3b79473-63b0-40da-9cd1-7e8e9d5548de.png)

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated
![Captura de Pantalla 2022-03-04 a la(s) 10 55 29](https://user-images.githubusercontent.com/21312057/156776845-fd49ba8a-4c80-4488-bde5-1d5499666608.png)

- [X] Check the targets page to make sure the vaccines given this month widget updates (restricted users only)
![Captura de Pantalla 2022-03-04 a la(s) 10 55 52](https://user-images.githubusercontent.com/21312057/156776870-4aecfb81-31a5-40df-a900-cb5f3ece8b8c.png)

3. Send an immunization form for the child using the SMS form (IMM).

- [X] Make sure the condition card updates to reflect the vaccination
![Captura de Pantalla 2022-03-04 a la(s) 10 59 53](https://user-images.githubusercontent.com/21312057/156776895-458d8a9b-3629-40c9-bb4e-63a425b3257c.png)

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated
![Captura de Pantalla 2022-03-04 a la(s) 11 00 03](https://user-images.githubusercontent.com/21312057/156776920-969d4385-1fe0-4f69-a4c5-e5cf4fcc1b28.png)

- [X] Check the targets page to make sure the vaccines given this month widget updates
![Captura de Pantalla 2022-03-04 a la(s) 11 00 20](https://user-images.githubusercontent.com/21312057/156776938-bf5ed541-930f-4ffe-a9ef-40b41fad0fa2.png)

**Comment by lorerod** [comment]
**Config:** Standard
 **Environment:** gamma-cht.dev
**Platform:** WebApp 
**Browser:** Chrome

1. Add a new child under 2 to your clinic using the SMS CW form. The health center needs to be configured with immunization use cases.

- [X] Make sure the Medic ID field gets populated (you may have to wait briefly for Sentinel to generate the ID)
<img width="743" alt="Captura de Pantalla 2022-03-16 a la(s) 15 09 37" src="https://user-images.githubusercontent.com/21312057/158659417-f3d5d13f-1003-4efe-a5cc-e2f0d66215ce.png">

- [X] Check the record in Reports to make sure the appropriate SMS schedule is generated
<img width="1024" alt="Captura de Pantalla 2022-03-16 a la(s) 15 09 58" src="https://user-images.githubusercontent.com/21312057/158659456-165b200c-ffbb-4270-9e55-c12651dd8f99.png">

2. Process an immunization visit form for the child through the web app.

- [X] Make sure the condition card updates to reflect the visit
<img width="673" alt="Captura de Pantalla 2022-03-16 a la(s) 15 11 58" src="https://user-images.githubusercontent.com/21312057/158659492-62ce700d-a370-4a5d-b391-01c0f51a67ec.png">

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated
<img width="1019" alt="Captura de Pantalla 2022-03-16 a la(s) 15 12 15" src="https://user-images.githubusercontent.com/21312057/158659517-98aea7ba-478c-4f0c-a3df-de6551e3a1ee.png">

- [X] Check the targets page to make sure the vaccines given this month widget updates (restricted users only)
<img width="316" alt="Captura de Pantalla 2022-03-16 a la(s) 15 12 29" src="https://user-images.githubusercontent.com/21312057/158659537-dfa3bdf7-c023-4bad-9d3f-cc6d8760139c.png">

3. Send an immunization form for the child using the SMS form (IMM).

- [X] Make sure the condition card updates to reflect the vaccination
<img width="376" alt="Captura de Pantalla 2022-03-16 a la(s) 15 14 21" src="https://user-images.githubusercontent.com/21312057/158659572-a28523a2-3684-403f-9ea5-53ad35a57cdc.png">

- [X] Check the record in Reports to make sure the appropriate outgoing SMS is generated
<img width="595" alt="Captura de Pantalla 2022-03-16 a la(s) 15 14 34" src="https://user-images.githubusercontent.com/21312057/158659589-52d589ef-0e1c-4f19-b4b2-859680538c65.png">

- [X] Check the targets page to make sure the vaccines given this month widget updates
<img width="204" alt="Captura de Pantalla 2022-03-16 a la(s) 15 14 44" src="https://user-images.githubusercontent.com/21312057/158659605-f705ac8c-67c8-4475-87be-2eac1ab133b0.png">

**Comment by tatilepizs** [comment]
### **Immunization Workflow**

**User:** CHW
**Config:** Standard
 **Environment:** gamma-cht
**Platform:** WebApp 
**Browser:** Chrome

<details>
<summary>New child under 2 years created (CW form).</summary>

![image](https://user-images.githubusercontent.com/94494491/164768546-c74c0e45-a682-4cdd-a971-bdc97cbbb8a7.png)
![image](https://user-images.githubusercontent.com/94494491/164768876-aec5d683-4736-4215-8fbb-869123d9a779.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164769036-21260230-166c-4134-9857-2e091853d725.png)
![image](https://user-images.githubusercontent.com/94494491/164769192-cb22f406-57b5-48b4-bb2e-7dfc606ce9f1.png)

</details>

<details>
<summary>Immunization visit for the child created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164769336-ef834f53-def6-41f3-9b5d-88b492a51a53.png)
![image](https://user-images.githubusercontent.com/94494491/164769526-0d4329bf-7cfb-4575-9a2a-a97dca09da03.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164769587-e249a20b-800b-43bb-b054-e2efa5d17c98.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/164780561-d0a3741a-fa2d-4460-8ba5-36f9e0491866.png)

</details>

<details>
<summary>Immunization visit for the child created (IMM form).</summary>

![image](https://user-images.githubusercontent.com/94494491/164781794-4c668b84-0f7e-41f5-bdda-8d33f9d6f61e.png)
![image](https://user-images.githubusercontent.com/94494491/164781759-c3775e6e-2984-45e1-96e6-a13d35464549.png)

</details>

<details>
<summary>Record in reports created.</summary>

![image](https://user-images.githubusercontent.com/94494491/164781853-780f3a8f-cf3c-4fbc-8f6c-8b145f4c48a4.png)
![image](https://user-images.githubusercontent.com/94494491/164781883-34011c3c-6181-4808-9a83-8430928c09af.png)

</details>

<details>
<summary>Targets updated.</summary>

![image](https://user-images.githubusercontent.com/94494491/164781925-d981fd9e-4b28-4e34-9fc3-443f22d90ad5.png)

</details>
