### ISSUE TITLE
Upgrade to latest release and ensure app works.

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#55]
**User:** Admin/ Offline User/ Online User 
**Site:** Standard Config
**Platform:** Desktop With Chrome, Mobile App
**Test Steps**:   
Using an instance with the last release and possibly further back.
Update to this release version.
Use a large amount of docs(10K + ) on a offline user. Upgrade server and then upgrade the phone. 
Ex: 3.2 -> 3.3 or 2.18 -> 3.2.

**Expected Result**: 
Ensure the app has updated properly and is usable. 
Users are prompted to update since the settings, app cache, of doc changes. This is dependent on what changes are in the release. 
Large Doc Counts: Ensure the app is usable.

**Comment by ngaruko** [comment]
Errors in console, not affecting upgrade (from 3.7.1 to 3.8.0)
![image](https://user-images.githubusercontent.com/6979995/71790726-be0d6d00-3096-11ea-993b-8dc1d60e246d.png)
