### ISSUE TITLE
Purging of documents

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#56]
**User:** Admin User
**Site:** Standard config site
**Platform:** Chrome Desktop

Current docs are here. [Purging](https://docs.communityhealthtoolkit.org/apps/guides/performance/purging/)

Also refer to [medic/cht-core#6181](https://github.com/medic/cht-core/issues/6181)  Purging for task and target documents 

and 
[medic/cht-core#5902](https://github.com/medic/cht-core/issues/5902) - Offline users download all their previous feedback docs 

Validate purging clears docs only specified by the purge function. 
Validate purging doesn't occur upstream. A new database should be created that contains the docs that are purged and the user should only replicate what's required.

**Comment by meghna-khemka** [comment]
Issuw working fine
![image](https://user-images.githubusercontent.com/84743933/125653404-b3cdcf9a-5ee3-43e6-895a-1c2ec4c0ad47.png)
