### ISSUE TITLE
Submit an SMS pregnancy visit form for pregnant woman on standard config as restricted user on mobile app

### ISSUE THREAD

**Issue by newtewt** [medic/cht-release-testing#8]
**User**: Restricted User
**Site**: Standard config site
**Platform**:  Mobile App
**Test Steps**:
From the admin app 
Process a new SMS pregnancy form(P) to a newly created woman created by the SMS N form. 
Submit an SMS pregnancy visit with form V. Use the from number of the restricted user. 

**Expected Result**:
Make sure the condition card updates to reflect the visit
Check the record in Reports to make sure the appropriate outgoing SMS is generated

**Comment by tatilepizs** [comment]
## Testing plan for MoH Uganda upgrade

**cht-core version:** 4.1
**cht-android version:** 0.8.5

| Tester | Phone details | Android version | Results | Notes |
|-|-|-|-|-|
| Bede | | | | |
| Lorena | | | | |
| Tatiana | | | | |
